# 数据集参数
dataset_args:
  dataset_name: tky
  data_root: ./data
  min_poi_freq: 9
  min_user_freq: 9
  session_time_interval: 1440
  num_spatial_slots: 3000
  spatial_slot_type: linear
  only_last_metric: True
  max_d_epsilon: 5

# 模型参数
model_args:
  model_name: "Meta-Llama-3-8B-Instruct"
  model_path: "./downloaded_model"
  temperature: 0.7
  max_input_length: 4096
  max_output_length: 128
  device: "cuda"
  top_k: 20
  max_steps: 5
  reflection_frequency: 3
  max_reflection_tokens: 100
  reflection_strategy: "HIERARCHICAL"

# 训练参数
run_args:
  seed: 27486607
  gpu: -1
  batch_size: 64
  eval_batch_size: 64
  do_train: True
  do_validate: True
  do_test: True
  max_steps: 100000
  epoch: 1
  valid_steps: 500
  save_path: "./checkpoints"

# 日志参数
logging_args:
  log_dir: "logs"
  model_dir: "checkpoints"
  tensorboard_dir: "runs"
  logging_steps: 100